### ISSUE TITLE
tomli not correctly installed as a dependency

### ISSUE THREAD

**Issue by dueyfinster** [trickeydan/hue2mqtt-python#22]
On latest MacOS (Sonoma 14.2):

```
➜  ~ pip install hue2mqtt            
Collecting hue2mqtt
  Downloading hue2mqtt-0.4.1-py3-none-any.whl.metadata (7.0 kB)
Collecting aiohttp<4.0.0,>=3.8.1 (from hue2mqtt)
  Downloading aiohttp-3.9.1-cp310-cp310-macosx_11_0_arm64.whl.metadata (7.4 kB)
Collecting aiohue<3.0.0,>=2.5.1 (from hue2mqtt)
  Downloading aiohue-2.6.3-py3-none-any.whl (17 kB)
Collecting click<9.0.0,>=8.1.3 (from hue2mqtt)
  Downloading click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting gmqtt<0.7.0,>=0.6.10 (from hue2mqtt)
  Downloading gmqtt-0.6.13-py3-none-any.whl.metadata (8.7 kB)
Collecting pydantic<2.0.0,>=1.9.2 (from hue2mqtt)
  Downloading pydantic-1.10.13-cp310-cp310-macosx_11_0_arm64.whl.metadata (149 kB)
     ━━━━━━━━━━━━━━━ 149.6/149.6 kB 3.4 MB/s eta 0:00:00
Collecting attrs>=17.3.0 (from aiohttp<4.0.0,>=3.8.1->hue2mqtt)
  Downloading attrs-23.1.0-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━ 61.2/61.2 kB 6.8 MB/s eta 0:00:00
Collecting multidict<7.0,>=4.5 (from aiohttp<4.0.0,>=3.8.1->hue2mqtt)
  Downloading multidict-6.0.4-cp310-cp310-macosx_11_0_arm64.whl (29 kB)
Collecting yarl<2.0,>=1.0 (from aiohttp<4.0.0,>=3.8.1->hue2mqtt)
  Downloading yarl-1.9.4-cp310-cp310-macosx_11_0_arm64.whl.metadata (31 kB)
Collecting frozenlist>=1.1.1 (from aiohttp<4.0.0,>=3.8.1->hue2mqtt)
  Downloading frozenlist-1.4.0-cp310-cp310-macosx_11_0_arm64.whl.metadata (5.2 kB)
Collecting aiosignal>=1.1.2 (from aiohttp<4.0.0,>=3.8.1->hue2mqtt)
  Downloading aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting async-timeout<5.0,>=4.0 (from aiohttp<4.0.0,>=3.8.1->hue2mqtt)
  Downloading async_timeout-4.0.3-py3-none-any.whl.metadata (4.2 kB)
Collecting typing-extensions>=4.2.0 (from pydantic<2.0.0,>=1.9.2->hue2mqtt)
  Downloading typing_extensions-4.9.0-py3-none-any.whl.metadata (3.0 kB)
Collecting idna>=2.0 (from yarl<2.0,>=1.0->aiohttp<4.0.0,>=3.8.1->hue2mqtt)
  Downloading idna-3.6-py3-none-any.whl.metadata (9.9 kB)
Downloading hue2mqtt-0.4.1-py3-none-any.whl (14 kB)
Downloading aiohttp-3.9.1-cp310-cp310-macosx_11_0_arm64.whl (386 kB)
   ━━━━━━━━━━━━━━━━ 386.5/386.5 kB 11.6 MB/s eta 0:00:00
Downloading click-8.1.7-py3-none-any.whl (97 kB)
   ━━━━━━━━━━━━━━━━━━━ 97.9/97.9 kB 7.9 MB/s eta 0:00:00
Downloading gmqtt-0.6.13-py3-none-any.whl (30 kB)
Downloading pydantic-1.10.13-cp310-cp310-macosx_11_0_arm64.whl (2.5 MB)
   ━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 19.7 MB/s eta 0:00:00
Downloading async_timeout-4.0.3-py3-none-any.whl (5.7 kB)
Downloading frozenlist-1.4.0-cp310-cp310-macosx_11_0_arm64.whl (46 kB)
   ━━━━━━━━━━━━━━━━━━━ 46.0/46.0 kB 4.4 MB/s eta 0:00:00
Downloading typing_extensions-4.9.0-py3-none-any.whl (32 kB)
Downloading yarl-1.9.4-cp310-cp310-macosx_11_0_arm64.whl (79 kB)
   ━━━━━━━━━━━━━━━━━━━ 79.2/79.2 kB 6.1 MB/s eta 0:00:00
Downloading idna-3.6-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━ 61.6/61.6 kB 5.6 MB/s eta 0:00:00
Installing collected packages: typing-extensions, multidict, idna, gmqtt, frozenlist, click, attrs, async-timeout, yarl, pydantic, aiosignal, aiohttp, aiohue, hue2mqtt
Successfully installed aiohttp-3.9.1 aiohue-2.6.3 aiosignal-1.3.1 async-timeout-4.0.3 attrs-23.1.0 click-8.1.7 frozenlist-1.4.0 gmqtt-0.6.13 hue2mqtt-0.4.1 idna-3.6 multidict-6.0.4 pydantic-1.10.13 typing-extensions-4.9.0 yarl-1.9.4
➜  ~ vim hue2mqtt.toml                         
➜  ~ hue2mqtt -c hue2mqtt.toml 
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/hue2mqtt/config.py", line 13, in <module>
    import tomllib  # type: ignore[import,unused-ignore]
ModuleNotFoundError: No module named 'tomllib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/hue2mqtt", line 5, in <module>
    from hue2mqtt.app import app
  File "/opt/homebrew/lib/python3.10/site-packages/hue2mqtt/app.py", line 8, in <module>
    from .hue2mqtt import Hue2MQTT
  File "/opt/homebrew/lib/python3.10/site-packages/hue2mqtt/hue2mqtt.py", line 31, in <module>
    from .config import Hue2MQTTConfig
  File "/opt/homebrew/lib/python3.10/site-packages/hue2mqtt/config.py", line 15, in <module>
    import tomli as tomllib  # type: ignore[import,no-redef,unused-ignore]
ModuleNotFoundError: No module named 'tomli'
➜  ~ pip install tomli        
Collecting tomli
  Downloading tomli-2.0.1-py3-none-any.whl (12 kB)
Installing collected packages: tomli
Successfully installed tomli-2.0.1
➜  ~ hue2mqtt -c hue2mqtt.toml
```

After installing tomli I could get it working. Thanks!

**Comment by trickeydan** [comment]
@dueyfinster Thanks for the report, there was an issue with the version constraints (`tomllib` isn't in the stdlib until 3.11).

Released v0.4.2 that fixes this issue. (You'll still need `tomli` installed on Python 3.10)
