### ISSUE TITLE
Errors when starting hue2mqtt

### ISSUE THREAD

**Issue by juhjar** [trickeydan/hue2mqtt-python#5]
Hi,

I'm trying to setup hue2mqtt on Raspberry Pi (Raspbian GNU/Linux 11 (bullseye), Python 3.9.2). 
Unfortunately some errors are generated and as my Python knowldege is very low, I can't figure what's the problem.
Config file is default. 

Is it normal that on each --discovery (and press of button on bridge) user name is different? 
Bridge version: BSB002 | 1.49.1949203030

Hopefully you can help on this matter. Thank You.

-juha

![hue2mqtt](https://user-images.githubusercontent.com/39704135/154242946-5f74ee36-b03f-4683-9f36-c9cf760d2ea8.png)

**Comment by trickeydan** [comment]
Hi @juhjar

Please could you send me the output with hue2mqtt in verbose mode?

e.g `hue2mqtt -v`

**Comment by juhjar** [comment]
` hue2mqtt -v -c /usr/local/etc/hue2mqtt.toml
2022-02-16 12:55:21 hue2mqtt hue2mqtt.hue2mqtt INFO Hue2MQTT v0.3.0 - Hue to MQTT Bridge.
2022-02-16 12:55:21 hue2mqtt hue2mqtt.mqtt.wrapper DEBUG MQTT Auth enabled
2022-02-16 12:55:21 hue2mqtt gmqtt.mqtt.protocol INFO [CONNECTION MADE]
2022-02-16 12:55:21 hue2mqtt gmqtt.mqtt.handler DEBUG [CMD 0x20] b'\x00\x00'
2022-02-16 12:55:21 hue2mqtt gmqtt.mqtt.handler DEBUG [CONNACK] flags: 0x0, result: 0x0
2022-02-16 12:55:21 hue2mqtt hue2mqtt.mqtt.wrapper DEBUG Subscribing to hue2mqtt/light/+/set
2022-02-16 12:55:21 hue2mqtt gmqtt.mqtt.utils DEBUG NEW ID: 1
2022-02-16 12:55:21 hue2mqtt gmqtt.mqtt.package INFO [SEND SUB] 1 [b'hue2mqtt/light/+/set']
2022-02-16 12:55:21 hue2mqtt hue2mqtt.mqtt.wrapper DEBUG Subscribing to hue2mqtt/group/+/set
2022-02-16 12:55:21 hue2mqtt gmqtt.mqtt.utils DEBUG NEW ID: 2
2022-02-16 12:55:21 hue2mqtt gmqtt.mqtt.package INFO [SEND SUB] 2 [b'hue2mqtt/group/+/set']
2022-02-16 12:55:21 hue2mqtt gmqtt.client DEBUG [QoS query IS EMPTY]
2022-02-16 12:55:21 hue2mqtt hue2mqtt.hue2mqtt INFO Connected to MQTT Broker
2022-02-16 12:55:21 hue2mqtt hue2mqtt.hue2mqtt INFO Connecting to Hue Bridge at 192.168.2.94
2022-02-16 12:55:22 hue2mqtt gmqtt.mqtt.handler DEBUG [CMD 0x90] b'\x00\x01\x00'
2022-02-16 12:55:22 hue2mqtt gmqtt.mqtt.handler INFO [SUBACK] 1 (0,)
2022-02-16 12:55:22 hue2mqtt gmqtt.mqtt.utils DEBUG FREE MID: 1
2022-02-16 12:55:22 hue2mqtt gmqtt.mqtt.handler DEBUG [CMD 0x90] b'\x00\x02\x00'
2022-02-16 12:55:22 hue2mqtt gmqtt.mqtt.handler INFO [SUBACK] 2 (0,)
2022-02-16 12:55:22 hue2mqtt gmqtt.mqtt.utils DEBUG FREE MID: 2
2022-02-16 12:55:22 hue2mqtt aiohue.bridge.192.168.2.94 DEBUG Unused result: {'schedules': {'1': {'name': 'Hue dimmer switch 2', 'description': '11:timer ', 'command': {'address': '/api/0/sensors/10/state', 'body': {'status': 1}, 'method': 'PUT'}, 'localtime': 'PT00:00:10', 'time': 'PT00:00:10', 'created': '2022-02-15T20:41:35', 'status': 'disabled', 'autodelete': False, 'starttime': '2022-02-15T20:41:35', 'recycle': True}, '3': {'name': 'Tuomas Hue dimmer switch 1', 'description': '11:timer ', 'command': {'address': '/api/0/sensors/8/state', 'body': {'status': 1}, 'method': 'PUT'}, 'localtime': 'PT00:00:10', 'time': 'PT00:00:10', 'created': '2022-02-07T19:46:57', 'status': 'disabled', 'autodelete': False, 'starttime': '2022-02-07T19:46:57', 'recycle': True}}, 'rules': {'1': {'name': '12:', 'owner': '17d15747-348f-4a2e-997a-25f98388e8b7', 'created': '2022-02-06T18:24:16', 'lasttriggered': '2022-02-15T20:41:35', 'timestriggered': 7, 'status': 'enabled', 'recycle': True, 'conditions': [{'address': '/sensors/4/state/buttonevent', 'operator': 'eq', 'value': '1002'}, {'address': '/sensors/4/state/lastupdated', 'operator': 'dx'}, {'address': '/sensors/10/state/status', 'operator': 'gt', 'value': '0'}], 'actions': [{'address': '/groups/3/action', 'method': 'PUT', 'body': {'scene': 'sEMObgCiFv8ozh1'}}, {'address': '/sensors/10/state', 'method': 'PUT', 'body': {'status': 0}}, {'address': '/sensors/11/state', 'method': 'PUT', 'body': {'status': 1}}, {'address': '/schedules/1', 'method': 'PUT', 'body': {'status': 'enabled', 'localtime': 'PT00:00:10'}}]}, '2': {'name': '12:', 'owner': '17d15747-348f-4a2e-997a-25f98388e8b7', 'created': '2022-02-06T18:24:17', 'lasttriggered': '2022-02-15T20:35:32', 'timestriggered': 3, 'status': 'enabled', 'recycle': True, 'conditions': [{'address': '/sensors/4/state/buttonevent', 'operator': 'eq', 'value': '1002'}, {'address': '/sensors/4/state/lastupdated', 'operator': 'dx'}, {'address': '/sensors/10/state/status', 'operator': 'lt', 'value': '1'}, {'address': '/sensors/11/state/status', 'operator': 'eq', 'value': '1'}], 'actions': [{'address': '/sensors/11/state', 'method': 'PUT', 'body': {'status': 2}}, {'address': '/groups/3/action', 'method': 'PUT', 'body': {'scene': 'uzlvXA2aXCCqmav'}}, {'address': '/schedules/1', 'method': 'PUT', 'body': {'status': 'enabled', 'localtime': 'PT00:00:10'}}]}, '3': {'name': '12:', 'owner': '17d15747-348f-4a2e-997a-25f98388e8b7', 'created': '2022-02-06T18:24:17', 'lasttriggered': '2022-02-15T20:19:15', 'timestriggered': 1, 'status': 'enabled', 'recycle': True, 'conditions': [{'address': '/sensors/4/state/buttonevent', 'operator': 'eq', 'value': '1002'}, {'address': '/sensors/4/state/lastupdated', 'operator': 'dx'}, {'address': '/sensors/10/state/status', 'operator': 'lt', 'value': '1'}, {'address': '/sensors/11/state/status', 'operator': 'eq', 'value': '2'}], 'actions': [{'address': '/sensors/11/state', 'method': 'PUT', 'body': {'status': 3}}, {'address': '/groups/3/action', 'method': 'PUT', 'body': {'scene': 'y744m7FSYATFl4J'}}, {'address': '/schedules/1', 'method': 'PUT', 'body': {'status': 'enabled', 'localtime': 'PT00:00:10'}}]}, '4': {'name': '12:', 'owner': '17d15747-348f-4a2e-997a-25f98388e8b7', 'created': '2022-02-06T18:24:17', 'lasttriggered': '2022-02-15T20:19:17', 'timestriggered': 1, 'status': 'enabled', 'recycle': True, 'conditions': [{'address': '/sensors/4/state/buttonevent', 'operator': 'eq', 'value': '1002'}, {'address': '/sensors/4/state/lastupdated', 'operator': 'dx'}, {'address': '/sensors/10/state/status', 'operator': 'lt', 'value': '1'}, {'address': '/sensors/11/state/status', 'operator': 'eq', 'value': '3'}], 'actions': [{'address': '/sensors/11/state', 'method': 'PUT', 'body': {'status': 4}}, {'address': '/groups/3/action', 'method': 'PUT', 'body': {'scene': 'TTgxqK5j5JJXlii'}}, {'address': '/schedules/1', 'method': 'PUT', 'body': {'status': 'enabled', 'localtime': 'PT00:00:10'}}]}, '5': {'name': '12:', 'owner': '17d15747-348f-4a2e-997a-25f98388e8b7', 'created': '2022-02-06T18:24:17', 'lasttriggered': 'none', 'timestriggered': 0, 'status': 'enabled', 'recycle': True, 'conditions': [{'address': '/sensors/4/state/buttonevent', 'operator': 'eq', 'value': '1002'}, {'address': '/sensors/4/state/lastupdated', 'operator': 'dx'}, {'address': '/sensors/10/state/status', 'operator': 'lt', 'value': '1'}, {'address': '/sensors/11/state/status', 'operator': 'eq', 'value': '4'}], 'actions': [{'address': '/sensors/11/state', 'method': 'PUT', 'body': {'status': 5}}, {'address': '/groups/3/action', 'method': 'PUT', 'body': {'scene': 'wJdgQNT5UA8QWK8'}}, {'address': '/schedules/1', 'method': 'PUT', 'body': {'status': 'enabled', 'localtime': 'PT00:00:10'}}]}, '6': {'name': '12:', 'owner': '17d15747-348f-4a2e-997a-25f98388e8b7', 'created': '2022-02-06T18:24:17', 'lasttriggered': 'none', 'timestriggered': 0, 'status': 'enabled', 'recycle': True, 'conditions': [{'address': '/sensors/4/state/buttonevent', 'operator': 'eq', 'value': '1002'}, {'address': '/sensors/4/state/lastupdated', 'operator': 'dx'}, {'address': '/sensors/10/state/status', 'operator': 'lt', 'value': '1'}, {'address': '/sensors/11/state/status', 'operator': 'eq', 'value': '5'}], 'actions': [{'address': '/sensors/11/state', 'method': 'PUT', 'body': {'status': 1}}, {'address': '/groups/3/action', 'method': 'PUT', 'body': {'scene': 'sEMObgCiFv8ozh1'}}, {'address': '/schedules/1', 'method': 'PUT', 'body': {'status': 'enabled', 'localtime': 'PT00:00:10'}}]}, '7': {'name': '13:', 'owner': '17d15747-348f-4a2e-997a-25f98388e8b7', 'created': '2022-02-06T18:24:17', 'lasttriggered': '2022-02-15T20:37:39', 'timestriggered': 2, 'status': 'enabled', 'recycle': True, 'conditions': [{'address': '/sensors/4/state/buttonevent', 'operator': 'eq', 'value': '2000'}, {'address': '/sensors/4/state/lastupdated', 'operator': 'dx'}], 'actions': [{'address': '/groups/3/action', 'method': 'PUT', 'body': {'transitiontime': 9, 'bri_inc': 30}}]}, '8': {'name': '14:', 'owner': '17d15747-348f-4a2e-997a-25f98388e8b7', 'created': '2022-02-06T18:24:18', 'lasttriggered': 'none', 'timestriggered': 0, 'status': 'enabled', 'recycle': True, 'conditions': [{'address': '/sensors/4/state/buttonevent', 'operator': 'eq', 'value': '3000'}, {'address': '/sensors/4/state/lastupdated', 'operator': 'dx'}], 'actions': [{'address': '/groups/3/action', 'method': 'PUT', 'body': {'transitiontime': 9, 'bri_inc': -30}}]}, '9': {'name': '15:', 'owner': '17d15747-348f-4a2e-997a-25f98388e8b7', 'created': '2022-02-06T18:24:18', 'lasttriggered': 'none', 'timestriggered': 0, 'status': 'enabled', 'recycle': True, 'conditions': [{'address': '/sensors/4/state/buttonevent', 'operator': 'eq', 'value': '2001'}, {'address': '/sensors/4/state/lastupdated', 'operator': 'dx'}], 'actions': [{'address': '/groups/3/action', 'method': 'PUT', 'body': {'transitiontime': 9, 'bri_inc': 56}}]}, '10': {'name': '16:', 'owner': '17d15747-348f-4a2e-997a-25f98388e8b7', 'created': '2022-02-06T18:24:18', 'lasttriggered': 'none', 'timestriggered': 0, 'status': 'enabled', 'recycle': True, 'conditions': [{'address': '/sensors/4/state/buttonevent', 'operator': 'eq', 'value': '3001'}, {'address': '/sensors/4/state/lastupdated', 'operator': 'dx'}], 'actions': [{'address': '/groups/3/action', 'method': 'PUT', 'body': {'transitiontime': 9, 'bri_inc': -56}}]}, '11': {'name': '17:', 'owner': '17d15747-348f-4a2e-997a-25f98388e8b7', 'created': '2022-02-06T18:24:18', 'lasttriggered': '2022-02-15T20:50:23', 'timestriggered': 2, 'status': 'enabled', 'recycle': True, 'conditions': [{'address': '/sensors/4/state/buttonevent', 'operator': 'eq', 'value': '4000'}, {'address': '/sensors/4/state/lastupdated', 'operator': 'dx'}], 'actions': [{'address': '/sensors/10/state', 'method': 'PUT', 'body': {'status': 1}}, {'address': '/groups/3/action', 'method': 'PUT', 'body': {'on': False}}]}, '12': {'name': '12:', 'owner': '17d15747-348f-4a2e-997a-25f98388e8b7', 'created': '2022-02-06T18:22:41', 'lasttriggered': 'none', 'timestriggered': 0, 'status': 'enabled', 'recycle': True, 'conditions': [{'address': '/sensors/2/state/buttonevent', 'operator': 'eq', 'value': '1002'}, {'address': '/sensors/2/state/lastupdated', 'operator': 'dx'}, {'address': '/sensors/8/state/status', 'operator': 'gt', 'value': '0'}], 'actions': [{'address': '/groups/2/action', 'method': 'PUT', 'body': {'scene': 'KCxHHN8b3ucsKO-'}}, {'address': '/sensors/8/state', 'method': 'PUT', 'body': {'status': 0}}, {'address': '/sensors/9/state', 'method': 'PUT', 'body': {'status': 1}}, {'address': '/schedules/3', 'method': 'PUT', 'body': {'status': 'enabled', 'localtime': 'PT00:00:10'}}]}, '13': {'name': '12:', 'owner': '17d15747-348f-4a2e-997a-25f98388e8b7', 'created': '2022-02-06T18:22:41', 'lasttriggered': 'none', 'timestriggered': 0, 'status': 'enabled', 'recycle': True, 'conditions': [{'address': '/sensors/2/state/buttonevent', 'operator': 'eq', 'value': '1002'}, {'address': '/sensors/2/state/lastupdated', 'operator': 'dx'}, {'address': '/sensors/8/state/status', 'operator': 'lt', 'value': '1'}, {'address': '/sensors/9/state/status', 'operator': 'eq', 'value': '1'}], 'actions': [{'address': '/sensors/9/state', 'method': 'PUT', 'body': {'status': 2}}, {'address': '/groups/2/action', 'method': 'PUT', 'body': {'scene': 'jh6c7GbFzQtHMeD'}}, {'address': '/schedules/3', 'method': 'PUT', 'body': {'status': 'enabled', 'localtime': 'PT00:00:10'}}]}, '27': {'name': '12:', 'owner': '17d15747-348f-4a2e-997a-25f98388e8b7', 'created': '2022-02-06T18:22:42', 'lasttriggered': 'none', 'timestriggered': 0, 'status': 'enabled', 'recycle': True, 'conditions': [{'address': '/sensors/2/state/buttonevent', 'operator': 'eq', 'value': '1002'}, {'address': '/sensors/2/state/lastupdated', 'operator': 'dx'}, {'address': '/sensors/8/state/status', 'operator': 'lt', 'value': '1'}, {'address': '/sensors/9/state/status', 'operator': 'eq', 'value': '2'}], 'actions': [{'address': '/sensors/9/state', 'method': 'PUT', 'body': {'status': 3}}, {'address': '/groups/2/action', 'method': 'PUT', 'body': {'scene': 'xEeNWO5gO6a1koq'}}, {'address': '/schedules/3', 'method': 'PUT', 'body': {'status': 'enabled', 'localtime': 'PT00:00:10'}}]}, '28': {'name': '12:', 'owner': '17d15747-348f-4a2e-997a-25f98388e8b7', 'created': '2022-02-06T18:22:42', 'lasttriggered': 'none', 'timestriggered': 0, 'status': 'enabled', 'recycle': True, 'conditions': [{'address': '/sensors/2/state/buttonevent', 'operator': 'eq', 'value': '1002'}, {'address': '/sensors/2/state/lastupdated', 'operator': 'dx'}, {'address': '/sensors/8/state/status', 'operator': 'lt', 'value': '1'}, {'address': '/sensors/9/state/status', 'operator': 'eq', 'value': '3'}], 'actions': [{'address': '/sensors/9/state', 'method': 'PUT', 'body': {'status': 4}}, {'address': '/groups/2/action', 'method': 'PUT', 'body': {'scene': 'Dr2YpVMtwUkJn9k'}}, {'address': '/schedules/3', 'method': 'PUT', 'body': {'status': 'enabled', 'localtime': 'PT00:00:10'}}]}, '29': {'name': '12:', 'owner': '17d15747-348f-4a2e-997a-25f98388e8b7', 'created': '2022-02-06T18:22:42', 'lasttriggered': 'none', 'timestriggered': 0, 'status': 'enabled', 'recycle': True, 'conditions': [{'address': '/sensors/2/state/buttonevent', 'operator': 'eq', 'value': '1002'}, {'address': '/sensors/2/state/lastupdated', 'operator': 'dx'}, {'address': '/sensors/8/state/status', 'operator': 'lt', 'value': '1'}, {'address': '/sensors/9/state/status', 'operator': 'eq', 'value': '4'}], 'actions': [{'address': '/sensors/9/state', 'method': 'PUT', 'body': {'status': 5}}, {'address': '/groups/2/action', 'method': 'PUT', 'body': {'scene': 'DegJNPSlFrizMaB'}}, {'address': '/schedules/3', 'method': 'PUT', 'body': {'status': 'enabled', 'localtime': 'PT00:00:10'}}]}, '30': {'name': '12:', 'owner': '17d15747-348f-4a2e-997a-25f98388e8b7', 'created': '2022-02-06T18:22:42', 'lasttriggered': 'none', 'timestriggered': 0, 'status': 'enabled', 'recycle': True, 'conditions': [{'address': '/sensors/2/state/buttonevent', 'operator': 'eq', 'value': '1002'}, {'address': '/sensors/2/state/lastupdated', 'operator': 'dx'}, {'address': '/sensors/8/state/status', 'operator': 'lt', 'value': '1'}, {'address': '/sensors/9/state/status', 'operator': 'eq', 'value': '5'}], 'actions': [{'address': '/sensors/9/state', 'method': 'PUT', 'body': {'status': 1}}, {'address': '/groups/2/action', 'method': 'PUT', 'body': {'scene': 'KCxHHN8b3ucsKO-'}}, {'address': '/schedules/3', 'method': 'PUT', 'body': {'status': 'enabled', 'localtime': 'PT00:00:10'}}]}, '31': {'name': '13:', 'owner': '17d15747-348f-4a2e-997a-25f98388e8b7', 'created': '2022-02-06T18:22:42', 'lasttriggered': 'none', 'timestriggered': 0, 'status': 'enabled', 'recycle': True, 'conditions': [{'address': '/sensors/2/state/buttonevent', 'operator': 'eq', 'value': '2000'}, {'address': '/sensors/2/state/lastupdated', 'operator': 'dx'}], 'actions': [{'address': '/groups/2/action', 'method': 'PUT', 'body': {'transitiontime': 9, 'bri_inc': 30}}]}, '32': {'name': '14:', 'owner': '17d15747-348f-4a2e-997a-25f98388e8b7', 'created': '2022-02-06T18:22:42', 'lasttriggered': 'none', 'timestriggered': 0, 'status': 'enabled', 'recycle': True, 'conditions': [{'address': '/sensors/2/state/buttonevent', 'operator': 'eq', 'value': '3000'}, {'address': '/sensors/2/state/lastupdated', 'operator': 'dx'}], 'actions': [{'address': '/groups/2/action', 'method': 'PUT', 'body': {'transitiontime': 9, 'bri_inc': -30}}]}, '33': {'name': '15:', 'owner': '17d15747-348f-4a2e-997a-25f98388e8b7', 'created': '2022-02-06T18:22:43', 'lasttriggered': 'none', 'timestriggered': 0, 'status': 'enabled', 'recycle': True, 'conditions': [{'address': '/sensors/2/state/buttonevent', 'operator': 'eq', 'value': '2001'}, {'address': '/sensors/2/state/lastupdated', 'operator': 'dx'}], 'actions': [{'address': '/groups/2/action', 'method': 'PUT', 'body': {'transitiontime': 9, 'bri_inc': 56}}]}, '34': {'name': '16:', 'owner': '17d15747-348f-4a2e-997a-25f98388e8b7', 'created': '2022-02-06T18:22:43', 'lasttriggered': 'none', 'timestriggered': 0, 'status': 'enabled', 'recycle': True, 'conditions': [{'address': '/sensors/2/state/buttonevent', 'operator': 'eq', 'value': '3001'}, {'address': '/sensors/2/state/lastupdated', 'operator': 'dx'}], 'actions': [{'address': '/groups/2/action', 'method': 'PUT', 'body': {'transitiontime': 9, 'bri_inc': -56}}]}, '35': {'name': '17:', 'owner': '17d15747-348f-4a2e-997a-25f98388e8b7', 'created': '2022-02-06T18:22:43', 'lasttriggered': 'none', 'timestriggered': 0, 'status': 'enabled', 'recycle': True, 'conditions': [{'address': '/sensors/2/state/buttonevent', 'operator': 'eq', 'value': '4000'}, {'address': '/sensors/2/state/lastupdated', 'operator': 'dx'}], 'actions': [{'address': '/sensors/8/state', 'method': 'PUT', 'body': {'status': 1}}, {'address': '/groups/2/action', 'method': 'PUT', 'body': {'on': False}}]}}, 'resourcelinks': {'30492': {'name': 'Hue dimmer switch 2', 'description': 'Hue dimmer switch 2 behavior', 'type': 'Link', 'classid': 10013, 'owner': '17d15747-348f-4a2e-997a-25f98388e8b7', 'recycle': False, 'links': ['/rules/11', '/rules/10', '/rules/9', '/rules/8', '/rules/7', '/rules/6', '/rules/5', '/rules/4', '/rules/3', '/rules/2', '/rules/1', '/sensors/4', '/schedules/1', '/sensors/11', '/sensors/10', '/scenes/wJdgQNT5UA8QWK8', '/scenes/TTgxqK5j5JJXlii', '/scenes/y744m7FSYATFl4J', '/scenes/uzlvXA2aXCCqmav', '/scenes/sEMObgCiFv8ozh1', '/groups/3', '/lights/1']}, '5419': {'name': 'Tuomas Hue dimmer switch 1', 'description': 'Tuomas Hue dimmer switch 1 behavior', 'type': 'Link', 'classid': 10013, 'owner': '17d15747-348f-4a2e-997a-25f98388e8b7', 'recycle': False, 'links': ['/rules/35', '/rules/34', '/rules/33', '/rules/32', '/rules/31', '/rules/30', '/rules/29', '/rules/28', '/rules/27', '/rules/13', '/rules/12', '/sensors/2', '/schedules/3', '/sensors/9', '/sensors/8', '/scenes/DegJNPSlFrizMaB', '/scenes/Dr2YpVMtwUkJn9k', '/scenes/xEeNWO5gO6a1koq', '/scenes/jh6c7GbFzQtHMeD', '/scenes/KCxHHN8b3ucsKO-', '/groups/2', '/lights/2']}}}
2022-02-16 12:55:22 hue2mqtt hue2mqtt.hue2mqtt INFO Bridge Name: Philips hue
2022-02-16 12:55:22 hue2mqtt hue2mqtt.hue2mqtt INFO Bridge MAC: ec:bxxxxxxxx:32
2022-02-16 12:55:22 hue2mqtt hue2mqtt.hue2mqtt INFO API Version: 1.48.0
2022-02-16 12:55:22 hue2mqtt gmqtt.mqtt.package DEBUG Sending PUBLISH (q1), 'b'hue2mqtt/status'', ... (112 bytes)
2022-02-16 12:55:22 hue2mqtt gmqtt.mqtt.utils DEBUG NEW ID: 3
2022-02-16 12:55:22 hue2mqtt gmqtt.mqtt.package DEBUG Sending PUBLISH (q1), 'b'hue2mqtt/light/00:17:88:01:09:ad:a6:a3-0b'', ... (443 bytes)
2022-02-16 12:55:22 hue2mqtt gmqtt.mqtt.utils DEBUG NEW ID: 4
2022-02-16 12:55:22 hue2mqtt gmqtt.mqtt.package DEBUG Sending PUBLISH (q1), 'b'hue2mqtt/light/00:17:88:01:09:ad:a3:4b-0b'', ... (438 bytes)
2022-02-16 12:55:22 hue2mqtt gmqtt.mqtt.utils DEBUG NEW ID: 5
2022-02-16 12:55:22 hue2mqtt gmqtt.mqtt.package DEBUG Sending PUBLISH (q1), 'b'hue2mqtt/light/00:17:88:01:09:ad:a7:6f-0b'', ... (446 bytes)
2022-02-16 12:55:22 hue2mqtt gmqtt.mqtt.utils DEBUG NEW ID: 6
2022-02-16 12:55:22 hue2mqtt gmqtt.mqtt.package DEBUG Sending PUBLISH (q1), 'b'hue2mqtt/group/1'', ... (341 bytes)
2022-02-16 12:55:22 hue2mqtt gmqtt.mqtt.utils DEBUG NEW ID: 7
Traceback (most recent call last):
  File "/usr/local/bin/hue2mqtt", line 8, in <module>
    sys.exit(app())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/hue2mqtt/app.py", line 24, in app
    loop.run_until_complete(hue2mqtt.run())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/hue2mqtt/hue2mqtt.py", line 109, in run
    await self.main(websession)
  File "/usr/local/lib/python3.9/dist-packages/hue2mqtt/hue2mqtt.py", line 207, in main
    group = GroupInfo(id=id, **group_raw.raw)
  File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for GroupInfo
class
  field required (type=value_error.missing)`

**Comment by jonez7** [comment]
I have similar problem also that juhjar reported

**Comment by trickeydan** [comment]
@jonez7 @juhjar I have released v0.3.1 with a patch. Please update and confirm if your issue is resolved.
