### ISSUE TITLE
Missing State Error

### ISSUE THREAD

**Issue by trickeydan** [trickeydan/hue2mqtt-python#9]
The following issue was reported by @TimStallard

@TimStallard Please could you remind me what you had done to cause this error?

```
sensor data was:

Jun 18 16:17:13 homeauto hue2mqtt[997]: 2022-06-18 16:17:13 hue2mqtt hue2mqtt.hue2mqtt DEBUG {'state': {'buttonevent': None, 'lastupdated': 'none'}, 'swupdate': {'state': 'noupdates', 'lastinstall': '2019-11-02T23:02:41'}, 'config': {'on': True, 'battery': 85, 'reachable': True, 'pending': []}, 'name': 'Lounge switch', 'type': 'ZLLSwitch', 'modelid': 'RWL021',
'manufacturername': 'Signify Netherlands B.V.', 'productname': 'Hue dimmer switch', 'diversityid': '73bbabea-3420-499a-9856-46bf437e119b', 'swversion': '6.1.1.28573', 'uniqueid': '00:17:88:01:06:36:33:e1-02-fc00', 'capabilities': {'certified': True, 'primary': True, 'inputs': [{'repeatintervals': [800], 'events': [{'buttonevent': 1000, 'eventtype': 'initial_pre
ss'}, {'buttonevent': 1001, 'eventtype': 'repeat'}, {'buttonevent': 1002, 'eventtype': 'short_release'}, {'buttonevent': 1003, 'eventtype': 'long_release'}, {'buttonevent': 1004, 'eventtype': 'long_press'}]}, {'repeatintervals': [800], 'events': [{'buttonevent': 2000, 'eventtype': 'initial_press'}, {'buttonevent': 2001, 'eventtype': 'repeat'}, {'buttonevent': 2
002, 'eventtype': 'short_release'}, {'buttonevent': 2003, 'eventtype': 'long_release'}, {'buttonevent': 2004, 'eventtype': 'long_press'}]}, {'repeatintervals': [800], 'events': [{'buttonevent': 3000, 'eventtype': 'initial_press'}, {'buttonevent': 3001, 'eventtype': 'repeat'}, {'buttonevent': 3002, 'eventtype': 'short_release'}, {'buttonevent': 3003, 'eventtype'
: 'long_release'}, {'buttonevent': 3004, 'eventtype': 'long_press'}]}, {'repeatintervals': [800], 'events': [{'buttonevent': 4000, 'eventtype': 'initial_press'}, {'buttonevent': 4001, 'eventtype': 'repeat'}, {'buttonevent': 4002, 'eventtype': 'short_release'}, {'buttonevent': 4003, 'eventtype': 'long_release'}, {'buttonevent': 4004, 'eventtype': 'long_press'}]}
]}}

Jun 18 16:17:13 homeauto hue2mqtt[997]: Traceback (most recent call last):
Jun 18 16:17:13 homeauto hue2mqtt[997]:   File "/home/homeauto/homeauto-venv/bin/hue2mqtt", line 8, in <module>
Jun 18 16:17:13 homeauto hue2mqtt[997]:     sys.exit(app())
Jun 18 16:17:13 homeauto hue2mqtt[997]:   File "/home/homeauto/homeauto-venv/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
Jun 18 16:17:13 homeauto hue2mqtt[997]:     return self.main(*args, **kwargs)
Jun 18 16:17:13 homeauto hue2mqtt[997]:   File "/home/homeauto/homeauto-venv/lib/python3.9/site-packages/click/core.py", line 1062, in main
Jun 18 16:17:13 homeauto hue2mqtt[997]:     rv = self.invoke(ctx)
Jun 18 16:17:13 homeauto hue2mqtt[997]:   File "/home/homeauto/homeauto-venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
Jun 18 16:17:13 homeauto hue2mqtt[997]:     return ctx.invoke(self.callback, **ctx.params)
Jun 18 16:17:13 homeauto hue2mqtt[997]:   File "/home/homeauto/homeauto-venv/lib/python3.9/site-packages/click/core.py", line 763, in invoke
Jun 18 16:17:13 homeauto hue2mqtt[997]:     return __callback(*args, **kwargs)
Jun 18 16:17:13 homeauto hue2mqtt[997]:   File "/home/homeauto/homeauto-venv/lib/python3.9/site-packages/hue2mqtt/app.py", line 24, in app
Jun 18 16:17:13 homeauto hue2mqtt[997]:     loop.run_until_complete(hue2mqtt.run())
Jun 18 16:17:13 homeauto hue2mqtt[997]:   File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
Jun 18 16:17:13 homeauto hue2mqtt[997]:     return future.result()
Jun 18 16:17:13 homeauto hue2mqtt[997]:   File "/home/homeauto/homeauto-venv/lib/python3.9/site-packages/hue2mqtt/hue2mqtt.py", line 109, in run
Jun 18 16:17:13 homeauto hue2mqtt[997]:     await self.main(websession)
Jun 18 16:17:13 homeauto hue2mqtt[997]:   File "/home/homeauto/homeauto-venv/lib/python3.9/site-packages/hue2mqtt/hue2mqtt.py", line 214, in main
Jun 18 16:17:13 homeauto hue2mqtt[997]:     sensor = SensorInfo(id=id, **sensor_raw.raw)
Jun 18 16:17:13 homeauto hue2mqtt[997]:   File "pydantic/main.py", line 406, in pydantic.main.BaseModel.__init__
Jun 18 16:17:13 homeauto hue2mqtt[997]: pydantic.error_wrappers.ValidationError: 18 validation errors for SensorInfo
Jun 18 16:17:13 homeauto hue2mqtt[997]: state -> lastupdated
Jun 18 16:17:13 homeauto hue2mqtt[997]:   invalid datetime format (type=value_error.datetime)
Jun 18 16:17:13 homeauto hue2mqtt[997]: state -> presence
Jun 18 16:17:13 homeauto hue2mqtt[997]:   field required (type=value_error.missing)
Jun 18 16:17:13 homeauto hue2mqtt[997]: state -> lastupdated
Jun 18 16:17:13 homeauto hue2mqtt[997]:   invalid datetime format (type=value_error.datetime)
Jun 18 16:17:13 homeauto hue2mqtt[997]: state -> rotaryevent
Jun 18 16:17:13 homeauto hue2mqtt[997]:   field required (type=value_error.missing)
Jun 18 16:17:13 homeauto hue2mqtt[997]: state -> expectedrotation
Jun 18 16:17:13 homeauto hue2mqtt[997]:   field required (type=value_error.missing)
Jun 18 16:17:13 homeauto hue2mqtt[997]: state -> expectedeventduration
Jun 18 16:17:13 homeauto hue2mqtt[997]:   field required (type=value_error.missing)
Jun 18 16:17:13 homeauto hue2mqtt[997]: state -> lastupdated
Jun 18 16:17:13 homeauto hue2mqtt[997]:   invalid datetime format (type=value_error.datetime)
Jun 18 16:17:13 homeauto hue2mqtt[997]: state -> buttonevent
Jun 18 16:17:13 homeauto hue2mqtt[997]:   none is not an allowed value (type=type_error.none.not_allowed)
Jun 18 16:17:13 homeauto hue2mqtt[997]: state -> lastupdated
Jun 18 16:17:13 homeauto hue2mqtt[997]:   invalid datetime format (type=value_error.datetime)
Jun 18 16:17:13 homeauto hue2mqtt[997]: state -> dark
Jun 18 16:17:13 homeauto hue2mqtt[997]:   field required (type=value_error.missing)
Jun 18 16:17:13 homeauto hue2mqtt[997]: state -> daylight
Jun 18 16:17:13 homeauto hue2mqtt[997]:   field required (type=value_error.missing)
Jun 18 16:17:13 homeauto hue2mqtt[997]: state -> lightlevel
Jun 18 16:17:13 homeauto hue2mqtt[997]:   field required (type=value_error.missing)
Jun 18 16:17:13 homeauto hue2mqtt[997]: state -> lastupdated
Jun 18 16:17:13 homeauto hue2mqtt[997]:   invalid datetime format (type=value_error.datetime)
Jun 18 16:17:13 homeauto hue2mqtt[997]: state -> temperature
Jun 18 16:17:13 homeauto hue2mqtt[997]:   field required (type=value_error.missing)
Jun 18 16:17:13 homeauto hue2mqtt[997]: state -> lastupdated
Jun 18 16:17:13 homeauto hue2mqtt[997]:   invalid datetime format (type=value_error.datetime)
Jun 18 16:17:13 homeauto hue2mqtt[997]: state -> humidity
Jun 18 16:17:13 homeauto hue2mqtt[997]:   field required (type=value_error.missing)
Jun 18 16:17:13 homeauto hue2mqtt[997]: state -> lastupdated
Jun 18 16:17:13 homeauto hue2mqtt[997]:   invalid datetime format (type=value_error.datetime)
Jun 18 16:17:13 homeauto hue2mqtt[997]: state -> open
Jun 18 16:17:13 homeauto hue2mqtt[997]:   field required (type=value_error.missing)
```

**Comment by TimStallard** [comment]
Powercycling a hue hub and then restarting hue2mqtt before a switch has been pressed for the first time I think
